{"name": "test_get_all_user_forward[1846030109260034050-True-200-操作成功]", "status": "failed", "statusDetails": {"message": "AssertionError: 接口请求失败，状态码是 【 405 】 \nassert False == True\n +  where False = <api.result_api.ResultBase object at 0x000002429D6D6460>.success", "trace": "self = <testcases.api_test.user_test.test_02_get_user.TestGetAllUser object at 0x000002429D5E4430>\nget_admin_token_fixture = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyYmFjLXVzZXIiLCJpc3MiOiJsb25nY2hhbyIsImlhdCI6MTczMDcwMTU5MywiZXhwIjoxNzMwNzA1MTkzLCJpZCI6MTg0NjAzMDEwOTI2MDAzNDA1MH0.pL6Uth-LNzRE92QyjjaNdV5WMyumFXr7WzL5ENvKpMI'\nuserId = 1846030109260034050, expect_result = True, expect_code = 200\nexpect_msg = '操作成功'\n\n    @allure.story(\"用例--获取指定用户-正向\")\n    @allure.description(\"该用例是针对获取所有用户接口的测试\")\n    @pytest.mark.single\n    @pytest.mark.parametrize(\"userId, expect_result, expect_code, expect_msg\",\n                             api_data[\"test_get_user_forward\"])\n    # @pytest.mark.usefixtures(\"get_admin_token_fixture\")\n    def test_get_all_user_forward(self,get_admin_token_fixture,userId,  expect_result, expect_code, expect_msg):\n        logger.info(\"*************** 开始执行用例 ***************\")\n        token=get_admin_token_fixture\n        result = get_user(token,userId)\n>       assert_results(result,expect_result, expect_code, expect_msg)\n\ntest_02_get_user.py:23: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nresult = <api.result_api.ResultBase object at 0x000002429D6D6460>\nexpect_result = True, expect_code = 200, expect_msg = '操作成功'\n\n    def assert_results(result, expect_result, expect_code, expect_msg):\n        \"\"\"\n        断言结果并记录日志。\n        参数:\n            result: 实际结果对象，应该包含success, error, data等属性。\n            expect_result: 期望的成功状态。\n            expect_code: 期望的返回code。\n            expect_msg: 期望的返回message。\n        \"\"\"\n    \n        # 断言实际结果与期望结果相同\n>       assert result.success == expect_result, result.error\nE       AssertionError: 接口请求失败，状态码是 【 405 】 \nE       assert False == True\nE        +  where False = <api.result_api.ResultBase object at 0x000002429D6D6460>.success\n\n..\\..\\conftest.py:25: AssertionError"}, "description": "该用例是针对获取所有用户接口的测试", "attachments": [{"name": "log", "source": "4e3a4ec9-9f9f-4a33-9d82-fccea9263aab-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "userId", "value": "1846030109260034050"}, {"name": "expect_result", "value": "True"}, {"name": "expect_code", "value": "200"}, {"name": "expect_msg", "value": "'操作成功'"}], "start": 1730701593787, "stop": 1730701593793, "uuid": "7e4c397f-f14e-4548-807b-b3b663e9a9c0", "historyId": "19c51d2cc0bc7293043dcc6c5009d856", "testCaseId": "7f2740fd59fa1ecb2e61906b75a50d48", "fullName": "testcases.api_test.user_test.test_02_get_user.TestGetAllUser#test_get_all_user_forward", "labels": [{"name": "feature", "value": "用户模块"}, {"name": "epic", "value": "针对单个接口的测试"}, {"name": "story", "value": "用例--获取指定用户-正向"}, {"name": "tag", "value": "single"}, {"name": "parentSuite", "value": "testcases.api_test.user_test"}, {"name": "suite", "value": "test_02_get_user"}, {"name": "subSuite", "value": "TestGetAllUser"}, {"name": "host", "value": "CQCA202413058N"}, {"name": "thread", "value": "23872-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.api_test.user_test.test_02_get_user"}]}